# -*- coding: utf-8 -*-
"""Experiment7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t_-fFgbRRamc9uq8_Bopb0m-_33-uBnM
"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report

import matplotlib.pyplot as plt

df = pd.read_csv(
    '/content/sample_data/placement_predict_50k Dataset.csv'

)

print(df.head())

df = df.drop(
    columns=['IsAnomaly']
)

print(df.shape)

for col in df.columns:

    if pd.api.types.is_numeric_dtype(df[col]):

        df[col] = df[col].fillna(
            df[col].median()
        )

    else:

        df[col] = df[col].fillna(
            df[col].mode()[0]
        )

print("Missing values:")
print(df.isna().sum().sum())

df_encoded = pd.get_dummies(
    df,
    columns=[
        'Gender',
        'City',
        'CollegeTier',
        'Stream',
        'Specialisation',
        'Hostel',
        'HistoryOfBacklogs',
        'ExtraCurricular'
    ],
    drop_first=True
)

print(df_encoded.head())

cgpa_tier_mapping = {
    'Low': 0,
    'Mid': 1,
    'High': 2
}
df_encoded['CGPA_Tier'] = df_encoded['CGPA_Tier'].map(cgpa_tier_mapping)

print(df_encoded['CGPA_Tier'].value_counts())

X = df_encoded.drop(
    columns=['PlacementStatus']
)

y = df_encoded['PlacementStatus']

print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

y_pred = model.predict(
    X_test
)

print(y_pred)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

print(
    classification_report(
        y_test,
        y_pred
    )
)

plt.figure(
    figsize=(20, 10)
)

plot_tree(
    model,
    feature_names=X.columns,
    class_names=[
        'Not Placed',
        'Placed'
    ],
    filled=True,
    fontsize=7
)

plt.tight_layout()

plt.show()

plt.figure(
    figsize=(20, 10)
)

plot_tree(
    model,
    feature_names=X.columns,
    class_names=[
        'Not Placed',
        'Placed'
    ],
    filled=True,
    fontsize=7
)

plt.tight_layout()

plt.savefig(
    'decision_tree.png',
    dpi=150
)

print("Saved tree image.")





import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

RANDOM_STATE = 42

df = df_encoded.copy()

print("Sample of the dataset:")
print(df.head())

print(
    f"\nDataset shape: {df.shape}"
)

print(
    f"Class balance:\n{df['PlacementStatus'].value_counts()}"
)

TARGET = "PlacementStatus"

DROP_COLS = [
    "StudentID"
]

feature_names = [
    c for c in df.columns
    if c not in [TARGET] + DROP_COLS
]

X = df[feature_names].values

y = df[TARGET].values

print("Features:")
print(feature_names)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=RANDOM_STATE
)

print(
    "Training shape:",
    X_train.shape
)

print(
    "Testing shape:",
    X_test.shape
)

rf = RandomForestClassifier(
    n_estimators=100,
    max_features="sqrt",
    oob_score=True,
    random_state=RANDOM_STATE
)

rf.fit(
    X_train,
    y_train
)

y_pred = rf.predict(
    X_test
)

print(y_pred)

test_accuracy = accuracy_score(
    y_test,
    y_pred
)

print(
    f"Test accuracy: {test_accuracy:.4f}"
)

print(
    f"OOB score: {rf.oob_score_:.4f}"
)

print(
    "\nClassification report:"
)

print(
    classification_report(
        y_test,
        y_pred
    )
)

print("Feature importances:")

for name, importance in sorted(
    zip(
        feature_names,
        rf.feature_importances_
    ),
    key=lambda x: -x[1]
):

    print(
        f"{name}: {importance:.4f}"
    )