# -*- coding: utf-8 -*-
"""python basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AcdiV8aeMw-a9m4_-JHnMTKduVeuObzW
"""

num = int(input("Enter a number = "))
if num % 2 == 0:
  print("Even")
else:
    print("Odd")

length = int(input("Enter length = "))
width = int(input("Enter width = "))
area = length*width
print("Area = ", area)

for i in range(1,101):
 print(i)



num = int(input("Enter a number = "))
fact = 1
for i in range(1, num + 1):
  fact = fact * i
  print("Factroial =  ", fact)

num = int(input("Enter a number: "))

rev = 0

while num > 0:
  digit = num % 10
  rev = rev * 10 + digit
  num = num // 10
print("Rerversed number ", rev)

def prime(num):
    count = 0

    for i in range(1, num + 1):
        if num % i == 0:
            count = count + 1

    if count == 2:
        print("Prime Number")
    else:
        print("Not a Prime Number")

n = int(input("Enter a number: "))
prime(n)

